# _quarto-alt.yml

project:
  type: book
  output-dir: docs

book:
  title: "The React Blueprint"
  subtitle: "Architect, Code, and Launch Modern Interfaces"
  author: "Amit Verma"
  date: "2025-07-18"
  cover-image: cover.png
  chapters:
    - index.qmd
    - intro.qmd
    - SetupReactAppLocallyInSeconds.qmd
    - ErrorBoundary.qmd
    - MockOrInterceptAPI.qmd


website:
  title: "The React Blueprint"
  repo-url: https://akv004.github.io/ReactJSTips/
  repo-actions: [edit, issue]
  site-url: https://akv004.github.io/ReactJSTips/
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Intro"
        href: intro.qmd
      - text: "SetupReactAppLocallyInSeconds"
        href: SetupReactAppLocallyInSeconds.qmd
      - text: "ErrorBoundary"
        href: ErrorBoundary.qmd
      - text: "MockOrInterceptAPI"
        href: MockOrInterceptAPI.qmd



format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
    number-sections: true
    self-contained: true
  epub:
    cover-image: cover.png
    toc: true
    number-sections: true
    self-contained: true

